server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # \u914D\u7F6E MyBatis \u914D\u7F6E\u6587\u4EF6\u8DEF\u5F84
  mapper-locations: classpath:mapper/*Mapper.xml
  # \u914D\u7F6E\u6570\u636E\u5E93\u5B9E\u4F53\u5305\u8DEF\u5F84
  type-aliases-package: com.qsl.springboot.dataobject
  configuration:
    # \u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true
    cache-enabled: true
    local-cache-scope: session

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: info
    com.qsl.springboot.dao: debug